### PR TITLE
Fix Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ElanHasson**
- Switched from cloudinit via http to cd (was causing issues)
- corrected hashed password
- added more ram to support Subiquity better
- changed boot_command to support iso

### CODE REVIEW

**Comment by David-VTUK** [comment]
Thanks for the PR! Just trying to clarify:

* What issues were you having with delivering the cloud-init payload over HTTP? This seems to be the preferred method
* The hashed password should work correctly (and is PackerBuilt!) - just tested and its working. Were you having issues with the password?
* RAM in the template should be enough - were you encountering issues, if so, what?

**Comment by ElanHasson** [comment]
Hi @David-VTUK,

1. I agree with preferred methodology, however I isolated that change and it allowed setup to continue, I was watching the console in vSphere and it would just hang for hours.
2. I was reading another post about the new automated install system in 20.04 and it gave an example on how to rehash the password. 
3. Added more RAM because that same doc page on ubuntu site comparing debian installer vs Subiquity required more RAM. I'm not terribly concerned with this as Rancher can configure the deployed nodes independently of this template definition. I can lower to 2GB if you like.

I also updated the ISO image as it was a 404  when I cloned the repo. Forgot to mention in the commit message.

What I do know, is it did not work "out of the box", I also added the variables template.

BTW, this is my first time using packer. It's pretty cool!

**Comment by ElanHasson** [comment]
BTW, https://virtjo.com/2020/build-ubuntu-vm-with-packer-on-vsphere/ is the post I'm referring to which I copied some of the configs from.

**Comment by ElanHasson** [comment]
@David-VTUK, please advise if I am doing something incorrect-- i'm using WSL2 to build images on-- all I know is switching from http cloudinit to ISO  worked.

**Comment by LinAnt** [comment]
@ElanHasson just a guess, but have you checked if your firewall is blocking incoming connections on the packer port?

Also, you can "force" a single port by adding

```
      "http_port_min": "8080",
      "http_port_max": "8080",
```

for testing :+1:

**Comment by David-VTUK** [comment]
I can't say I've ever had issues with providing cloud-init data over http, either directly or through CI builds. As @LinAnt alludes to - it's likely down to local config / firewall / NAT / etc. 

I'd rather not change all the respective templates to switch from HTTP to cdrom as I've never encountered anyone else having this issue.

I guess the difference in hashed passwords is I think I used MD5 for mine whereas you used SHA256?

**Comment by ElanHasson** [comment]
Hi @LinAnt , 18.04 went fine which uses the packer ports :)

@David-VTUK-- SHA512 -- Like I stated, I only used what that link above said to do and it worked fine.

The ISO URL was also a 404, so I fixed that as well. 

Happy to remove the cdrom change.

**Comment by ElanHasson** [comment]
closing this in favor of the fix for iso 404 issue, in #17

**Comment by ElanHasson** [comment]
To close the loop here I revisited my http vs iso for metadata..

Turns out it was due to me being in wsl2 and the port not being exposed to the VM 😅

Setting up a port forwarding rule on the windows side to the wsl2 interface made it all work like a charm.

**Pull request closed without merging**
